title: "AliNe - Nextflow Alignment pipeline (https://github.com/Juke34/AliNe)"

run_modules:
    - fastqc
    - fastp
    - bowtie2
    - hisat2
    - star
    - kallisto
    
module_order:
    - fastqc:
        name: "FastQC (raw)"
        path_filters:
          - "*raw_logs*"
    - fastp
    - fastqc:
        name: "FastQC (trimmed)"
        path_filters:
          - "*trimmed_logs*"
    # issue #2866 - bbmap
    - fastqc:
        name: "FastQC (bbmap)"
        path_filters:
          - "*bbmap_logs*"
    - bowtie2:
        name: "bowtie2"
    - fastqc:
        name: "FastQC (bowtie2)"
        path_filters:
          - "*bowtie2_logs*"
    - fastqc:
        name: "FastQC (bwaaln)"
        path_filters:
          - "*bwaaln_logs*"
    - fastqc:
        name: "FastQC (bwamem)"
        path_filters:
          - "*bwamem_logs*"
    - fastqc:
        name: "FastQC (bwasw)"
        path_filters:
          - "*bwasw_logs*"
    - fastqc:
        name: "FastQC (graphmap2)"
        path_filters:
          - "*graphmap2_logs*"
    - fastqc:
        name: "FastQC (hisat)"
        path_filters:
          - "*hisat_logs*"
    - hisat2
    - fastqc:
        name: "FastQC (hisat2)"
        path_filters:
          - "*hisat2_logs*"
    - kallisto
    - fastqc:
        name: "FastQC (kallisto)"
        path_filters:
          - "*kallisto_logs*"
    - fastqc:
        name: "FastQC (minimap2)"
        path_filters:
          - "*minimap2_logs*"
    - fastqc:
        name: "FastQC (nucmer)"
        path_filters:
          - "*nucmer_logs*"
    - fastqc:
        name: "FastQC (subread)"
        path_filters:
          - "*subread_logs*"
    - fastqc:
        name: "FastQC (sublong)"
        path_filters:
          - "*sublong_logs*"
    - star
    - fastqc:
        name: "FastQC (STAR)"
        path_filters:
          - "*star_logs*"
          - "*STAR_logs*"
    - fastqc:
        name: "FastQC (STARlong)"
        path_filters:
          - "*starlong_logs*"
          - "*STARlong_logs*"