title: "Nextflow Alignment pipeline"

run_modules:
    - fastqc
    - fastp
  #  - bbmap
    - bowtie2
    - bwa 
    - bwa-mem
    - hisat2
    - minimap2
    - mummer4
    - star
    - subread
    
module_order:
    - fastqc:
        name: "FastQC (raw)"
        path_filters:
          - "*raw_logs*"
    - fastp
    - fastqc:
        name: "FastQC (trimmed)"
        path_filters:
          - "*trimmed_logs*"
    # issue #2866 - bbmap
    - fastqc:
        name: "FastQC (bbmap)"
        path_filters:
          - "*bbmap_logs*"
    - bowtie2:
        name: "bowtie2"
    - fastqc:
        name: "FastQC (bowtie2)"
        path_filters:
          - "*bowtie2_logs*"
    - bwa
    - fastqc:
        name: "FastQC (bwaaln)"
        path_filters:
          - "*bwaaln_logs*"
    - bwa-mem
    - fastqc:
        name: "FastQC (bwamem)"
        path_filters:
          - "*bwamem_logs*"
    - bwa-sw
    - fastqc:
        name: "FastQC (bwasw)"
        path_filters:
          - "*bwasw_logs*"
    - graphmap2
    - fastqc:
        name: "FastQC (graphmap2)"
        path_filters:
          - "*graphmap2_logs*"
    - hisat2
    - fastqc:
        name: "FastQC (hisat2)"
        path_filters:
          - "*hisat2_logs*"
    - minimap2
    - fastqc:
        name: "FastQC (minimap2)"
        path_filters:
          - "*minimap2_logs*"
    - mummer4
    - fastqc:
        name: "FastQC (nucmer)"
        path_filters:
          - "*nucmer_logs*"
    - star
    - fastqc:
        name: "FastQC (star)"
        path_filters:
          - "*star_logs*"